apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agriculture.fullname" . }}-celery
spec:
  replicas: {{ .Values.celery.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "agriculture.name" . }}
      app.kubernetes.io/component: celery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "agriculture.name" . }}
        app.kubernetes.io/component: celery
    spec:
      containers:
        - name: celery
          image: "{{ .Values.celery.image.repository }}:{{ .Values.celery.image.tag }}"
          imagePullPolicy: {{ .Values.celery.image.pullPolicy }}

          command:
            {{- toYaml .Values.celery.command | nindent 12 }}

          env:
            {{- toYaml .Values.env | nindent 12 }}

          resources:
            {{- toYaml .Values.celery.resources | nindent 12 }}
