apiVersion: v1
kind: Service
metadata:
  name: {{ include "agriculture.fullname" . }}
  labels:
    {{- include "agriculture.labels" . | nindent 4 }}
spec:
  type: {{ .Values.django.service.type }}
  ports:
    - port: {{ .Values.django.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agriculture.selectorLabels" . | nindent 4 }}
