apiVersion: v1
kind: Service
metadata:
  name: {{ include "agriculture.fullname" . }}
  labels:
    app.kubernetes.io/name: agriculture
    app.kubernetes.io/instance: agriculture
    app: agriculture
spec:
  type: {{ .Values.django.service.type }}
  selector:
    app.kubernetes.io/name: agriculture
    app.kubernetes.io/instance: agriculture
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
