apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agriculture-agro
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Safaraliyev05/agriculture.git
    targetRevision: master
    path: agriculture
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: devops-pro

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
